### PR TITLE
Improve setup

### PR DESCRIPTION
**Pull request by vext01**
This branch improves setup.py.

I've test all this with `setup.py` develop. Seems to work a charm. OK for you Richard?

### CODE REVIEW

**Comment by vext01** [comment]
Also added dmenu integration in the form of a small shell script.

**Comment by vext01** [comment]
So do you reckon this looks OK?

**Comment by richlanc** [comment]
## Feedback
* We're renamed the command line interface from passout -> passout_cli. Isn't the "_cli" overkill? I would rather not type that every time.

**Comment by vext01** [comment]
The last commit reverts to using entry points, like you had originally.

I've noticed a strange bug in `python setup.py test`:

```
wilfred:passout> /tmp/ve/bin/py.test 
============================= test session starts ==============================
platform openbsd5 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/edd/source/passout, inifile: 
collected 20 items 

tests/test_cli.py ........
tests/test_lib.py ............

========================== 20 passed in 26.09 seconds ==========================
wilfred:passout> /tmp/ve/bin/python setup.py test
running test
running egg_info
writing requirements to passout.egg-info/requires.txt
writing passout.egg-info/PKG-INFO
writing top-level names to passout.egg-info/top_level.txt
writing dependency_links to passout.egg-info/dependency_links.txt
writing entry points to passout.egg-info/entry_points.txt
reading manifest file 'passout.egg-info/SOURCES.txt'
writing manifest file 'passout.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform openbsd5 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/edd/source/passout, inifile: 
collected 20 items 

tests/test_cli.py ........
tests/test_lib.py FFFFF..FFFFF
...
        if pipe.returncode != 0:
>           raise PassOutError("gpg returned non-zero")
E           PassOutError: gpg returned non-zero
...
```

I have no idea why this is happening, but my guess is that the envieonment is not being handled right somehow. At some point my ~/.gnupg got trashed, so I think GNUPGHOME was not set at some point. Any ideas?

*WARNING: BACK UP ~/.gnupg before running any tests*

**Comment by vext01** [comment]
Also backup your passout directory. As mine is full of crap now.

**Pull request merged**
